// main 项目起始包
package main

import "fmt"

// Add 求和函数
func Add(a, b int) int {
	return a + b
}

func main() {
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(2, 3))
	fmt.Println("Hello, World!")
	fmt.Println(Add(24114241, 3))

}
