name: Lint-PR
on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  lint-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - name: Run golangci-lint via reviewdog 🐶
        uses: reviewdog/action-golangci-lint@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml"
          reporter: github-pr-review
          level: warning